#springboot配置
spring:
  profiles:
    active: vm
  application:
    name: tlias-web-management
  #mysql连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #Spring Cache配置
  cache:
    type: redis  # 启用 Redis 缓存
    redis:
      time-to-live: 3600000ms
      cache-null-values: false
#mybatis配置
mybatis:
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    #如果字段名与属性名符合驼峰命名规则，mybatis会自动通过驼峰命名规则映射。驼峰命名规则：   abc_xyz    =>   abcXyz
    #- 表中字段名：abc_xyz
    #- 类中属性名：abcXyz
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  helper-dialect: mysql
#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javaweb1-ai-01
    region: cn-beijing

# SpringDoc OpenAPI 接口文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
